### ISSUE TITLE
trying to get it to work

### ISSUE THREAD

**Issue by nydal91** [Aoinu/ng2-twitter#1]
get this error:
 Unexpected value 'AuthorizedRequestService' imported by the module 'AppModule' , 
can i use this to get my twitter feed?

**Comment by Aoinu** [comment]
I tried importing this via angular-cli templete.
then, I cannot see the error but it doesn't work.
I think that's because breaking changes of angular.

I'll try to update this module compatible with latest angular version.

**Comment by Aoinu** [comment]
I updated modules.

I think the error: (`Unexpected value 'AuthorizedRequestService' imported by the module 'AppModule'`) is a angular-cli's problem .
angular/angular#11438
angular/angular-cli#2291

I found they work when I patch `webpack-build-common.ts`.
