### ISSUE TITLE
Issue with angular-cli build

### ISSUE THREAD

**Issue by andrewkdouglas** [Aoinu/ng2-twitter#2]
I am running angular 2.2.3 from the angular-cli template. When I run `ng serve` I get:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1):
Error: Ng2TwitterModule is not an NgModule
```

Any ideas?

**Comment by brucethomax** [comment]
Bump, so this doesn't work with the new ng2?

**Comment by Aoinu** [comment]
I changed this module into one service.
Please use TwitterService which is added in v0.3.0 instead of Ng2TwitterModule.
